# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa682b4ed969542578f9735911308120b452e7fff2e6e3a34725903228561e43fa21880cac6a8a67e347eb17c115fa720f4c4b76ceaf6423ddc790335753cdc8

test:
  secret_key_base: 7aeb04f0521d80d2430010a4fcd21d616824ae5290a2ed11c04c5ac08978214978dcff940247add5c26fbebf7bdb341d0817fd744696c509251e6b2836958547

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: ba1bc70af2990e3db79130872224e1178eb4a7b17b0994ef13e7e8d7eb3f03ec897956a88cee464e92a692145b175cffb8645b63bcdb65483b2b984acfcd5b99
